{% set version = '0.1.7' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-esquisse
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/esquisse_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/esquisse/esquisse_{{ version }}.tar.gz
  sha256: 56b1be328ad66aa6b9d43f0a235893c44f2b57c98e2d6dc0f498414411f37cd7

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcolorbrewer
    - r-ggplot2 >=3.0.0
    - r-ggthemes
    - r-htmltools
    - r-jsonlite
    - r-miniui
    - r-rstudioapi
    - r-scales
    - r-shiny >=1.0.0
    - r-shinywidgets >=0.4.1
    - r-stringi
    - r-viridislite
  run:
    - r-base
    - r-rcolorbrewer
    - r-ggplot2 >=3.0.0
    - r-ggthemes
    - r-htmltools
    - r-jsonlite
    - r-miniui
    - r-rstudioapi
    - r-scales
    - r-shiny >=1.0.0
    - r-shinywidgets >=0.4.1
    - r-stringi
    - r-viridislite

test:
  commands:
    - $R -e "library('esquisse')"           # [not win]
    - "\"%R%\" -e \"library('esquisse')\""  # [win]

about:
  home: https://github.com/dreamRs/esquisse
  license: GPL-3
  summary: A 'shiny' gadget to create 'ggplot2' charts interactively with drag-and-drop to map
    your variables. You can quickly visualize your data accordingly to their type, export
    to 'PNG' or 'PowerPoint', and retrieve the code to reproduce the chart.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: esquisse
# Type: Package
# Title: Explore and Visualize Your Data Interactively
# Version: 0.1.7
# Authors@R: c(person("Fanny", "Meyer", email = "fanny.meyer@dreamrs.fr", role = c("aut")), person("Victor", "Perrier", email = "victor.perrier@dreamrs.fr", role = c("aut", "cre")), person("Ian", "Carroll", comment = "Facets support", role = "ctb"))
# Description: A 'shiny' gadget to create 'ggplot2' charts interactively with drag-and-drop to map your variables. You can quickly visualize your data accordingly to their type, export to 'PNG' or 'PowerPoint', and retrieve the code to reproduce the chart.
# URL: https://github.com/dreamRs/esquisse
# BugReports: https://github.com/dreamRs/esquisse/issues
# License: GPL-3 | file LICENSE
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.0
# Imports: miniUI, rstudioapi, shiny (>= 1.0.0), htmltools, jsonlite, shinyWidgets (>= 0.4.1), ggplot2 (>= 3.0.0), ggthemes, RColorBrewer, viridisLite, scales, stringi
# Suggests: officer, rvg, rio, DT, testthat
# NeedsCompilation: no
# Packaged: 2018-11-14 09:12:27 UTC; perri
# Author: Fanny Meyer [aut], Victor Perrier [aut, cre], Ian Carroll [ctb] (Facets support)
# Maintainer: Victor Perrier <victor.perrier@dreamrs.fr>
# Repository: CRAN
# Date/Publication: 2018-11-14 09:30:03 UTC
