{% set version = "1.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-esquisse
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/esquisse_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/esquisse/esquisse_{{ version }}.tar.gz
  sha256: 1a983a0f3f55b1f85a3e2693ea951510a7bd5bd3bd43a87aaf2ca328dbde8815

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-datamods
    - r-ggplot2 >=3.0.0
    - r-htmltools
    - r-jsonlite
    - r-rlang >=0.3.1
    - r-rstudioapi
    - r-scales
    - r-shiny >=1.1.0
    - r-shinywidgets >=0.6.0
    - r-styler
  run:
    - r-base
    - r-datamods
    - r-ggplot2 >=3.0.0
    - r-htmltools
    - r-jsonlite
    - r-rlang >=0.3.1
    - r-rstudioapi
    - r-scales
    - r-shiny >=1.1.0
    - r-shinywidgets >=0.6.0
    - r-styler

test:
  commands:
    - $R -e "library('esquisse')"           # [not win]
    - "\"%R%\" -e \"library('esquisse')\""  # [win]

about:
  home: https://github.com/dreamRs/esquisse
  license: GPL-3.0-only
  summary: A 'shiny' gadget to create 'ggplot2' charts interactively with drag-and-drop to map your variables. You can quickly visualize your data accordingly to their type, export to 'PNG' or 'PowerPoint', and retrieve the code to reproduce the chart.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: esquisse
# Type: Package
# Title: Explore and Visualize Your Data Interactively
# Version: 0.2.2
# Authors@R: c(person("Fanny", "Meyer", email = "fanny.meyer@dreamrs.fr", role = c("aut")), person("Victor", "Perrier", email = "victor.perrier@dreamrs.fr", role = c("aut", "cre")), person("Ian", "Carroll", comment = "Facets support", role = "ctb"))
# Description: A 'shiny' gadget to create 'ggplot2' charts interactively with drag-and-drop to map your variables. You can quickly visualize your data accordingly to their type, export to 'PNG' or 'PowerPoint', and retrieve the code to reproduce the chart.
# URL: https://github.com/dreamRs/esquisse
# BugReports: https://github.com/dreamRs/esquisse/issues
# License: GPL-3 | file LICENSE
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# Imports: miniUI, rstudioapi, shiny (>= 1.0.0), htmltools, jsonlite, shinyWidgets (>= 0.4.1), ggplot2 (>= 3.0.0), ggthemes, hrbrthemes, RColorBrewer, scales, stringi, rlang (>= 0.3.1)
# Suggests: officer, rvg, rio, DT, testthat (>= 2.1.0), knitr
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-08-22 13:13:12 UTC; perri
# Author: Fanny Meyer [aut], Victor Perrier [aut, cre], Ian Carroll [ctb] (Facets support)
# Maintainer: Victor Perrier <victor.perrier@dreamrs.fr>
# Repository: CRAN
# Date/Publication: 2019-08-22 13:30:02 UTC
