{% set version = "0.1.7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-esquisse
  version: {{ version|replace("-", "_") }}

source:
  fn: esquisse_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/esquisse_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/esquisse/esquisse_{{ version }}.tar.gz
  sha256: 56b1be328ad66aa6b9d43f0a235893c44f2b57c98e2d6dc0f498414411f37cd7

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcolorbrewer
    - r-ggplot2
    - r-ggthemes
    - r-htmltools
    - r-jsonlite
    - r-miniui
    - r-rstudioapi
    - r-scales
    - r-shiny
    - r-shinywidgets
    - r-stringi
  run:
    - r-base
    - r-rcolorbrewer
    - r-ggplot2
    - r-ggthemes
    - r-htmltools
    - r-jsonlite
    - r-miniui
    - r-rstudioapi
    - r-scales
    - r-shiny
    - r-shinywidgets
    - r-stringi

test:
  commands:
    - $R -e "library('esquisse')"           # [not win]
    - "\"%R%\" -e \"library('esquisse')\""  # [win]

about:
  home: https://github.com/dreamRs/esquisse
  license: GPL-3
  summary: A 'shiny' gadget to create 'ggplot2' charts interactively with drag-and-drop to map
    your variables. You can quickly visualize your data accordingly to their type, export
    to 'PNG' or 'PowerPoint', and retrieve the code to reproduce the chart.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
