appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: P/nNhePozjK+igD5wXe70fHl53UNMa22cZaIYcV4trwHfIufUqifLoF1q6wKWX6/oB0A4C6g937K0VobW8esgpPThnpZHniab38LeBkQ2LwYZW+WJ0iIEZ7DetK93d+5LZm9VaYfpDUCF6jTbIec17h9M4N2venoZxrYHRSNK/FWO3n94Zc55GZxhVsfLrFiGbqLCgDUcDPiaIIu+OdARsdMhVL2+Nf7tHJ9ITjVE4VKMD9S9AAaQpGjMZIJ0LKXIL8ZoAjgCvSV0sKyZ59pFDfxcFtJNDmAb14BfNvuTl+5b4ttYN8xmRNpDOeA1BGyNARfNKMC8nRo2xTG60wp8DnnTfNX5YRRAcK1knjHB5lRGZpkcrPRDT+Uf/4TAz4NLj7EXJWBrTtpIXuRYUibf9vGlWLg1lgF3hZJP+mbia3W5Y9Hc3dyoBfGp3Vi2+aLbtQP+iYta6cmzc03Vmd1UnFeXaorFM5SFfJLTNIxto8FJBCMV1rppoDa6JFx7wuvgWZqeoqJF1QtP87u/lcTA4Djr9llHcZFfZDGet367AcVHy/XbivYsuzJmURs+Uk8vExGjPpH8EN3kCVjzY/3Qp9GVXEJv1p9sRDlCR7GveVLMS8Te98dDBVIU6kr3B9+18Bf89CC1Qqw6ef2Vj0E/xAeG7kLWgDWmFw9GPUDSFE=}
bot:
  automerge: true
